# Copyright (c) 2026 evenTra. All rights reserved.
name: eventra
description: evenTra - Smart Venue Management & Auditorium Booking System for Christ University
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  geolocator: ^13.0.1
  google_sign_in: ^6.2.1
  provider: ^6.1.1
  google_fonts: ^6.1.0
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  table_calendar: ^3.1.0
  fl_chart: ^0.66.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
